language: php

php:
  - 5.6

matrix:
  fast_finish: true

before_install:
  - sudo apt-get update > /dev/null

install:
  - sudo apt-get install -y --force-yes php5-mysql
  - composer self-update
  - composer install

script: vendor/bin/phpcs