# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.gameservice:
        class: Chrl\AppBundle\Service\GameService
        arguments: ['@buktopuha.telegram_bot_api', '%buktopuha.config%', '@doctrine.orm.entity_manager']

    app.update_receiver:
        class: Chrl\AppBundle\UpdateReceiver\UpdateReceiver
        arguments: ['@buktopuha.telegram_bot_api', '%buktopuha.config%', '@doctrine.orm.entity_manager', '@app.gameservice','@app.commandpool']
    app.commandpool:
        class: Chrl\AppBundle\GameAction\CommandPool
        arguments: ['@buktopuha.telegram_bot_api']
