# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.update_receiver:
        class: Chrl\AppBundle\UpdateReceiver\UpdateReceiver
        arguments: ['@buktopuha.telegram_bot_api', '%buktopuha.config%']
        